defaults.url=https://sentry.io/
defaults.org=oncallshift
defaults.project=oncallshift-mobile
# Using SENTRY_AUTH_TOKEN environment variable

# Disable source map uploads for builds without auth token
cli.executable=echo